### ISSUE TITLE
Docker changed the Gateway IP in 1.9

### ISSUE THREAD

**Issue by pirelenito** [dockito/vault#12]
Trying to run the vault using the README instructions:

``` bash
docker run -p 172.17.42.1:14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault
```

Resulted in the following error:

```
Error response from daemon: Cannot start container 9ba34fb583134b4d0fef08c442afeb16c544d1b1adc5152ad994feda954fa515: failed to create endpoint boring_jennings on network bridge: Error starting userland proxy: listen tcp 172.17.42.1:14242: bind: cannot assign requested address
```

Inspecting another running container, I could check that the Gateway has changed from `172.17.42.1`:

``` bash
"Gateway": "172.17.0.1"
```

And running the vault binding with the new IP fixes the probem:

``` bash
docker run -p 172.17.0.1:14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault
```

Before considering change the README, we need to confirm that this change is indeed consistent.

**Comment by esnunes** [comment]
The `docker0` default interface ip address was `172.17.42.1` however it is not guaranteed to be always the same. Looks like since version 1.9 docker has changed it to `172.17.0.1`. The best solution would be a command line relying on the `docker0` ip address, no matter its value.

the following command would fix the problem but it is quite complex:

``` bash
docker run -p `ifconfig docker0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}'`:14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault
```

**Comment by maxclaus** [comment]
May be just describe in the docs which IP use depending on the current  running docker version.

**Comment by pirelenito** [comment]
This is also a breaking change in the `ONVAULT` script, as it will point to the wrong IP.

We might need to rethink the strategy or have separated releases and some good error messages when something goes wrong.

**Comment by pirelenito** [comment]
see: https://github.com/dockito/vault/blob/master/ONVAULT#L7

**Comment by maxclaus** [comment]
This env variable already helps. Would be good include it in the docs: https://github.com/dockito/vault#environment-variables

And using tags for the images I guess would prevent any possible problem related with different docker versions.

**Comment by maxclaus** [comment]
@pirelenito this pull request https://github.com/dockito/vault/pull/15 fixed this problem. Can you close this issue now?

**Comment by pirelenito** [comment]
Agreed!
