### ISSUE TITLE
Question on process

### ISSUE THREAD

**Issue by jmoney** [dockito/vault#13]
This is the best way I can ask a question...

So what is the flow? It seems the app asks for some ssh keys from vault. However, there is no auth between vault and the running container(how could there be when this is the process for retrieving "secret zero").  So basically, any running container can ask for the ssh keys from vault so any malicious container can gain access to the ssh keys that can be used to grab things like passwords to a DB or oauth credz for a service? Did I miss a part of the flow or is that not what this process solves. 

Not asking this project to solve the issue just reading up on how others have solved "secret zero".

**Comment by pirelenito** [comment]
You are correct.

The main motivation behind vault is to fix secret access during `docker build` time, as currently there isn't an official solution.

And indeed any container running in the same machine would have access to the keys. That is why you must have it running in a controlled environment.

Did it answer your question?

For more information, check https://github.com/docker/docker/issues/6396#issuecomment-95637006

**Comment by maxclaus** [comment]
We could get a bit more security using auth keys to "load/access" the privates keys.

I think in the vault service could be included some env variables like this:

``` shell
# PRIVATE_KEY_<key-alias>_NAME: "name"
PRIVATE_KEY_IDRSA_NAME: "id_rsa"
# PRIVATE_KEY_<key-alias>_AUTHKEY: "secret"
PRIVATE_KEY_IDRSA_AUTHKEY: "my super secret"
```

And in the `ONVAULT` command we could add an argument to specify the private key authkey:

``` shell
# ONVAULT --authkey-<alias>="secret"
ONVAULT --authkey-idrsa="my super secret"
```

So in case the vault service has the private key configurations it will allow only access the configured private key if the request contains authkey for it.

**Comment by jmoney** [comment]
Sweet. Yes. This answered my question. Did not make the connection that this is only for build level secrets and not runtime level secrets. Thanks for answering!!
