### ISSUE TITLE
cp: cannot stat '/root/.ssh/*': No such file or directory with empty .ssh folder

### ISSUE THREAD

**Issue by Kukunin** [dockito/vault#19]
I don't have .ssh folder while image building, and I get this error:

```
Step 8 : RUN ONVAULT bundle install
 ---> Running in 0a49fc21a42d
cp: cannot stat '/root/.ssh/*': No such file or directory
The command '/bin/sh -c ONVAULT bundle install' returned a non-zero code: 1
```

In the image from previous step, I can inspect, that I have empty /root/.ssh folder, but `cp -r /root/.ssh/*` rejects to work with empty folders. If I do `touch /root/.ssh/1`, if works like a charm.

I use `FROM ruby:2.3` image

**Comment by maxclaus** [comment]
Sorry. My bad. I will fix it later today.
