### ISSUE TITLE
Do not use mktemp to create temp folders. Is not available in all Linux distros.

### ISSUE THREAD

**Issue by maxclaus** [dockito/vault#20]

**Comment by NikolausDemmel** [comment]
Do you have a suggestion of what else to use that is more portable?

What Linux distros would you want to see supported that don't have mktemp?

**Comment by maxclaus** [comment]
Alpine images by default do not have mktemp available. I guess something like this `mkdir "/tmp/dockito-vault-$(date +%s)"` should be enough for any distro.
