### ISSUE TITLE
Having to do a bunch of extra things to use keys

### ISSUE THREAD

**Issue by lukaso** [dockito/vault#5]
I'm having to do a bit of funny business to get everything to work. But maybe this is intentional.

Once I have the keys, I do:

```
RUN ONVAULT 'eval "$(ssh-agent -s)" && ssh-add && \
            cd $APP_HOME && git clone git@github.com:dockito/vault.git'
```

Note how I have to start `ssh-agent` and `ssh-add`. I wonder if those shouldn't be built into the `ONVAULT` command.

Also, adding the single quotes feels a bit redundant, but otherwise the commands don't work (because of the way `eval` is called.

**Comment by maxclaus** [comment]
With `ONVAULT` you shouldn't need to do all this. Here is an example:

```
FROM node:0.10.38

# installs Dockito Vault ONVAULT utility
# https://github.com/dockito/vault
RUN apt-get update -y && \
    apt-get install -y curl && \
    curl -L https://raw.githubusercontent.com/dockito/vault/master/ONVAULT > /usr/local/bin/ONVAULT && \
    chmod +x /usr/local/bin/ONVAULT


# Run anything depending on SSH through ONVAULT
RUN ONVAULT git clone git@github.com:dockito/vault.git

# The files are there and I didn't need to include any (ssh-agent or ssh-add)
RUN ls -l vault
```

**Comment by lukaso** [comment]
It is working as you say when the ssh key is `id_rsa`. When the key was named `github_docker_key`, I couldn't just call `ssh-add`, but had to start the key agent.

**Comment by maxclaus** [comment]
Indeed. I have always used the default key name and have never realised this problem. I will try make it customizable.

**Comment by maxclaus** [comment]
Done. Included an environment variable `VAULT_SSH_KEY` to specify custom ssh keys ([doc](https://github.com/dockito/vault#custom-configurations)). 

Could you check if it solves your problem?

**Comment by lukaso** [comment]
I solved the problem by putting my keys in a sub directory and changing the `docker run` command, and renaming the key to `id_rsa`. This would have solved that though. However, I don't want to bake the key names into my `Dockerfile` because that causes problems as well.

I've actually used it to add additional information into the ssh directory so this would be a more generalized secrets management system:

```
RUN ONVAULT AWS_ACCESS_KEY='`cat $HOME/.ssh/aws_access_key`' \
            AWS_SECRET_KEY='`cat $HOME/.ssh/aws_secret_key`' \
            bundle exec rake pull_files_from_aws
```

**Comment by maxclaus** [comment]
Yeah. You are right, for most cases including the key name in the Dockerfile would not work so well since each person building the image could use different ssh keys names. But I will keep this option because maybe there is some cases where that could be handy.

I realised the solution could be even simpler. As I said before each person can use different keys for each host. So anyone who uses an different ssh key could define it in the ssh config file:

```
# use this key for github host
Host github.com
IdentityFile ~/.ssh/github_docker_key

# or use this key for any host
Host *
IdentityFile ~/.ssh/github_docker_key
```

This way is not baked the key name into the Dockerfile and flexible for anyone use the right key for each host.

What do you think?

**Comment by lukaso** [comment]
I like this solution the best. Is this mostly a case of documenting that will work, or does it already work.

BTW, I've found I'm using ONVAULT for `docker run` commands as well, so I don't have to fool around with permissions.

**Comment by maxclaus** [comment]
I have included the documentation about the SSH config file. [here](https://github.com/dockito/vault#ssh-config-file)

**Comment by lukaso** [comment]
that's great.
